### PR TITLE
fix: _JSXStyle import is not found

### LINKED ISSUE #695: I got _JSXStyle is not defined with 3.4.0
👋 friend. Welcome to styled-jsx and thanks for contributing!

⚠️ IMPORTANT ⚠️

If you need help or have a question about styled-jsx please ask it on Spectrum https://spectrum.chat/styled-jsx or join our Slack community at https://zeit.chat and ask it in the `#next` channel.

Before you open a new issue please take a look at our [**Frequent Asked Questions**](https://github.com/zeit/styled-jsx#faq) and [**open issues**](https://github.com/zeit/styled-jsx/issues).

Remember, often time asking in chat or looking at the FAQ/issues can be *faster than waiting for us to reply to a new issue**.

If you are here to report a bug or request a feature please remove this introductory section and fill out the information below!

---

#### What is the current behavior?
when I use <style jsx> in MyComponent I got _JSXStyle is not defined
#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

1. webpack 4.42.0
2. mac 
3. 

#### Environment (include versions)

* OS:
* Browser:
* styled-jsx (version): 3.4.0

#### Did this work in previous versions?
yes

### LINKED ISSUE #696: import _JSXStyle2 from "styled-jsx/style"; when my components's props use destructuring
👋 friend. Welcome to styled-jsx and thanks for contributing!

⚠️ IMPORTANT ⚠️

If you need help or have a question about styled-jsx please ask it on Spectrum https://spectrum.chat/styled-jsx or join our Slack community at https://zeit.chat and ask it in the `#next` channel.

Before you open a new issue please take a look at our [**Frequent Asked Questions**](https://github.com/zeit/styled-jsx#faq) and [**open issues**](https://github.com/zeit/styled-jsx/issues).

Remember, often time asking in chat or looking at the FAQ/issues can be *faster than waiting for us to reply to a new issue**.

If you are here to report a bug or request a feature please remove this introductory section and fill out the information below!

---

#### What is the current behavior?

when i use destructuring in component, i will got an error about _JSXStyle because of `import _JSXStyle2 from "styled-jsx/style";` not `import _JSXStyle from "styled-jsx/style";`

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

1. webpack 4.32.2
2. @babel/core 7.4.5

#### What is the expected behavior?
normal working
#### Environment (include versions)

* OS: 
* Browser:
* styled-jsx (version): 3.4.0 and 3.4.1；both happen

### LINKED ISSUE #711: Uncaught ReferenceError: _JSXStyle is not defined | >v3.3.2 | CRA + react-app-rewired + customize-cra + Production Build
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behavior?
- Using the latest `styled-jsx` version, or any version newer than `v3.3.2` will produce a fatal error in the production build (when opened in the browser): `_JSXStyle is not defined`.
- Dependencies: create-rect-app, react-app-rewired, customize-cra.
- During development everything works as expected without any error.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

1. Create a new app with `create-react-app`.
2. Install `react-app-rewired` and `customize-cra`
3. Configure `config-override.js`:
``` 
const { override, useBabelRc } = require("customize-cra");

module.exports = override(
  useBabelRc("./.babelrc"),
);
```
4. Configure `.babelrc` (same behavior when using the `addBabelPlugin` feature of `customize-cra`):
```
{
  "presets": ["babel-preset-react-app"],
  "plugins": [
    [
      "styled-jsx/babel",
      {
        "plugins": [
          [
            "@styled-jsx/plugin-sass",
            {
              "sassOptions": {
                "includePaths": ["./src/styles"]
              }
            }
          ]
        ]
      }
    ]
  ]
}
```

Same error happens for this `.babelrc` config:
```
{
  "presets": ["babel-preset-react-app"],
  "plugins": ["styled-jsx/babel"]
}
```

When there is no `"plugins": ["styled-jsx/babel"]` in `.babelrc` it works as expected, but then it's not possible to add plugins.

5. `yarn run build` (`react-app-rewired build`) and `serve -s build` - or deploy to bucket/server
6. Fatal error happens: `Uncaught ReferenceError: _JSXStyle is not defined`

#### What is the expected behavior?
`styled-jsx` should work in production the same as in development.

#### Environment (include versions)

* OS: Any
* Browser: Any
* styled-jsx (version): >3.3.2

#### Did this work in previous versions?
It works with v3.3.2 but not in newer versions.

Could it be an issue with this? https://github.com/vercel/styled-jsx/pull/684

#### Fix for now
- Either do `import _JSXStyle from "styled-jsx/style";` for each file.
- Or hard-code `3.3.2` in `package.json`

### PR DESCRIPTION
**Pull request by huozhi**
### Chnages

Carry on work of #716 , generate import id in program scope

### Related

Fixes #695
Fixes #696
Fixes #711

### CODE REVIEW

File: src/_utils.js [hunk 1]
```diff
@@ -622,13 +622,45 @@ export const booleanOption = opts => {
...
+
+  const importIdentifier = addDefault(
     state.file.path,
     typeof state.opts.styleModule === 'string'
       ? state.opts.styleModule
       : 'styled-jsx/style',
-    { nameHint: STYLE_COMPONENT}
+    { nameHint: importIdentifierName }
   )
+  // const _JSXStyle = _JSXImport<uid>;
```
Comment (giuseppeg) [inline src/_utils.js:637]: If we don't want to fix this properly (see https://github.com/vercel/styled-jsx/pull/716#issuecomment-847161924 and https://github.com/vercel/styled-jsx/pull/716#issuecomment-847670031) I think that we can get rid of addDefault from @babel/helper-module-imports and create the default import manually and name it `STYLE_COMPONENT` as the following is redundant

```js
import _JSXImport_ref from 'styled-jsx/style';
const _JSXStyle = _JSXImport_ref;
```

We could have:

```js
import _JSXStyle from 'styled-jsx/style';
```

Comment (huozhi) [reply src/_utils.js:637]: I do hope we can fix it properly here...
I tried to follow the hint "we will have to generate the identifier (the name of the import specifier)" but I'm not super clear what you mean and finally come up with this. Can you hint more if there's approach to generate the more unique but consistent (not change among compiles) identifier in `Program` enter phase?

File: test/babel6/snapshots/external.js.md [hunk 2]
```diff
@@ -184,11 +188,13 @@ Generated by [AVA](https://ava.li).
...
 > Snapshot 1
 
-    `import _JSXStyle from 'styled-jsx/style';␊
+    `import _StyleImport3 from 'styled-jsx/style';␊
+    const _JSXStyle = _StyleImport3;␊
     import styles from './styles';␊
     const styles2 = require('./styles2');␊
     import { foo as styles3 } from './styles';␊
     ␊
+    export const _StyleImport = '123';␊
```
Comment (huozhi) [inline test/babel6/snapshots/external.js.md:197]: add a case that import identifier might have conflicts

File: src/_utils.js (hunk 1 above)
Comment (huozhi) [reply src/_utils.js]: I didn't get it first, thought the generated uid id `ref` are all sames in those cases..now moving import id creation to program enter phase, also update a test case for it. Does it match what you said? @giuseppeg

**Comment by masx200** [comment]
https://github.com/vercel/styled-jsx/issues/711#issuecomment-806852789


Why does this solve the problem?

File: src/_utils.js [hunk 3]
```diff
@@ -650,6 +655,7 @@ export const setStateOptions = state => {
       vendorPrefixes: state.opts.vendorPrefixes
     })
   }
+  state.styleComponent = STYLE_COMPONENT
```
Comment (giuseppeg) [inline src/_utils.js:658]:
```suggestion
```

The identifier should be generated in the `Program` visitor as a unique id https://github.com/vercel/styled-jsx/blob/master/src/babel.js#L286 and https://github.com/vercel/styled-jsx/blob/master/src/babel-external.js#L240

```js
state.styleComponentImportName = path.scope.generateUidIdentifier(STYLE_COMPONENT).node.name
```

Comment (huozhi) [reply src/_utils.js:658]: What about macro? It seems that macros cannot get the state property set in `Program` visitor.

File: test/babel6/snapshots/index.js.md [hunk 4]
```diff
@@ -19,7 +19,8 @@ Generated by [AVA](https://ava.li).
 
 > Snapshot 1
 
-    `const a = () => <div>␊
+    `import _JSXStyle from 'styled-jsx/style';␊
```
Comment (huozhi) [inline test/babel6/snapshots/index.js.md:22]: Need to find a way to erase the unused imports at the end

File: src/babel.js [hunk 5]
```diff
@@ -299,14 +311,12 @@ export default function({ types: t }) {
...
               !state.hasInjectedJSXStyle &&
-              !scope.hasBinding(STYLE_COMPONENT)
+              !scope.hasBinding(state.styleComponentImportName)
             )
           ) {
             return
           }
-
           state.hasInjectedJSXStyle = true
-          createReactComponentImportDeclaration(state)
```
Comment (giuseppeg) [inline src/babel.js:309]: this should be reverted

File: src/babel-external.js [hunk 6]
```diff
@@ -222,11 +225,9 @@ export const visitor = {
       if (
         hasJSXStyle &&
         taggedTemplateExpressions.resolve.length > 0 &&
-        !state.hasInjectedJSXStyle &&
-        !path.scope.hasBinding(STYLE_COMPONENT)
+        !state.hasInjectedJSXStyle
       ) {
         state.hasInjectedJSXStyle = true
-        createReactComponentImportDeclaration(state)
```
Comment (giuseppeg) [inline src/babel-external.js:229]: this should be reverted

File: src/babel.js [hunk 7]
```diff
@@ -283,9 +291,13 @@ export default function({ types: t }) {
           state.hasJSXStyle = null
           state.ignoreClosing = null
           state.file.hasJSXStyle = false
-
           setStateOptions(state)
 
+          // `addDefault` will generate unique id for the scope
+          state.styleComponentImportName = createReactComponentImportDeclaration(
+            state
+          )
```
Comment (giuseppeg) [inline src/babel.js:299]: Here you should only generate the unique identifier like I said in my previous comment.

`createReactComponentImportDeclaration` needs to be called only if when necessary (see the comments where I suggest to revert). This way the plugin won't insert imports when the lib is not used.

> Need to find a way to erase the unused imports at the end

Comment (huozhi) [reply src/babel.js:300]: If you created unique identifer first like `_JSXStyle`, then use it in `addDefault` will still generated a new one `_JSXStyle2` and skip the first one. So it will be useless anyway.

But some utils need to use  the import identifier before exit..like `processTaggedTemplateExpression`, or macro plugin. So I think we have to generate the cerntain id first, and let it be used.

I've add some chanegs to remove the unused imports at the end

File: src/babel.js [hunk 8]
```diff
@@ -294,19 +307,29 @@ export default function({ types: t }) {
...
+        exit(path, state) {
+          // For source that didn't really use styled-jsx imports,
+          // remove the injected import at the beginning
+          if (!state.file.hasJSXStyle && !state.file.hasCssImports) {
+            path.traverse({
+              ImportDeclaration(importPath) {
+                if (importPath.node.source.value === state.styleModule) {
+                  importPath.remove()
+                }
+              }
```
Comment (giuseppeg) [inline src/babel.js:319]: In CommonJS modules `addDefault` will not add ES6 imports and this visitor is not going to remove them. 

Do you know if `addDefault` returns a node or a path? If it returns the import statement or import specifier object (a `path`) that it injected you can store that in `state` and in Program.exit remove that path or closest import path.

File: src/_utils.js [hunk 9]
```diff
@@ -650,6 +658,10 @@ export const setStateOptions = state => {
       vendorPrefixes: state.opts.vendorPrefixes
     })
   }
+  state.styleModule =
+    typeof state.opts.styleModule === 'string'
+      ? state.opts.styleModule
+      : 'styled-jsx/style'
```
Comment (giuseppeg) [inline src/_utils.js:664]: we should document this in the readme

Comment (huozhi) [reply src/_utils.js:664]: We already have [this](https://github.com/vercel/styled-jsx#stylemodule), I just moved this part here from another place

File: src/babel.js (hunk 8 above)
Comment (huozhi) [reply src/babel.js:319]: `addDefault` returns a node of identifier type so no luck to delete conveniently.

Regarding to commonjs I'm not sure which case are you referring here. Do you mean if babel `option.sourceType` is `'unambiguous'`?

Comment (huozhi) [reply src/babel.js:319]: I'm not sure if pure commonjs source should be considered. Like we only handle the import declarations in babel-external. 

```js
const { css } = require("styled-jsx/css")
exports.name = css`div { color: red; }
```

If user writes the code above, plugin won't handle it either.

Comment (giuseppeg) [reply src/babel.js:319]: Oh ok! I'd need to look at the implementation because I don't remember if we support CommonJS. But if you can confirm that we don't then we don't even need to use addDefault and we can add the import ourselves like we were doing it before avoiding to insert the import and the remove it.

Comment (huozhi) [reply src/babel.js:319]: Yeah, this inconsistence was introduced in #684 but `styled-jsx/css` imports are not effected.

I wonder if we could ship this first since it will only inject unused require calls in pure commonjs sources with jsx style usage, and it could be tree-shaked by bundler.

This can resolve the current issue of "conflicted _JSXStyle name" and "undefined _JSXStyle" issues. (Also unblock some of react 18 integration work 😂.) 

I can file a PR later to change it back to previous imports injection if this plan sounds good to you.

File: src/_utils.js (hunk 3 above)
Comment (giuseppeg) [reply src/_utils.js]: Is this still an issue?

File: src/babel.js (hunk 8 above)
Comment (giuseppeg) [reply src/babel.js:319]: Sounds good!

**Review by giuseppeg — APPROVED** [review]
Thanks a lot for the contribution and for your immense patience Jiachi!

File: src/_utils.js (hunk 3 above)
Comment (huozhi) [reply src/_utils.js]: not anymore, will continue the import injection work later. thanks!
